# Generated by Django 4.2.11 on 2024-05-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pastel', models.BooleanField(default=False)),
            ],
        ),
    ]
